name: Ubuntu

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Start Building Ubuntu...
    runs-on: ubuntu-22.04

    steps:
      - name: Actualizando y Descargando dependencias...
        run: | 
          sudo apt-get install openssh-server
      - name: Configurando Servidor-SSH...
        run: | 
          sudo service sshd status
