name: Ubuntu

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Start Building Ubuntu...
    runs-on: ubuntu-22.04

    steps:
      # - name: Actualizando y Descargando dependencias...
      #   run: | 
      #     sudo apt-get install openssh-server
      - name: Chequiando estado del Servidor-SSH...
        run: | 
          sudo service sshd status & sudo ifconfig
      - name: Moviendoce al directorio SSH...
        run: |
          sudo cd /etc/ssh/ & sudo ls
